const refs = {
  filmListGallery: document.querySelector('.film-list_gallery'),
  filmCard: document.querySelector('.js-film-card'),
  inputEl: document.getElementById('input'),
  errorMessageEl: document.querySelector('.errorMessage'),
  lightbox: document.querySelector('.js-lightbox'),
  modalCloseBtn: document.querySelector('.modal-close-button'),
  aboutUs: document.querySelector('#about-us'),
  btnUp: document.querySelector('#btn-up'),
  filmListItem: document.querySelector('.film-list_item'),
  mainSection: document.querySelector('.section-main'),

  modal: document.querySelector('.modal'),
  bodyEl: document.querySelector('body'),
  switchInputEl: document.querySelector('.theme-switch__toggle'),
  paginationList: document.querySelector('.pagination-list'),
  paginationListMobile: document.querySelector('.pagination-list-mobile'),
  registrationBtn: document.querySelector('.registration-btn'),
  regLightbox: document.querySelector('.js-rf-lightbox'),
  regModalCloseBtn: document.querySelector('.rf-modal-close-button'),
  regModal: document.querySelector('.registration-modal'),
  signUpBtn: document.getElementById('signUp'),
  signInBtn: document.getElementById('signIn'),
  modalEl: document.querySelector('.rf-form'),
  myWatchedBtn: document.querySelector('.my-library_btn-watched'),
  myQueueBtn: document.querySelector('.my-library_btn-queue'),
  navigationLibraryEl: document.querySelector('.navigation_library'),
};

export { refs };
